server {
    listen 80;
    server_name crosscentral.wolframite.cc;

    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 300s;
    }

    location /_protected/ {
        internal;
        alias /srv/share/;
        autoindex off;
        sendfile on;
        tcp_nopush on;
        aio threads;
        add_header Accept-Ranges bytes;
    }
}
